// Edmark Reading Program — Level 1 vocabulary, in lesson order.
// Source: Level 1 Words in Order by Lesson Number. The three suffix lessons
// (-s, -ing, -ed) are omitted since they aren't standalone sight words.
//
// Zoe's reading game draws from the first PRACTICE_THROUGH_LESSON words — bump
// it as she progresses through the program.

export type SightWord = { n: number; word: string }

export const SIGHT_WORDS: SightWord[] = [
  { n: 1, word: 'horse' },
  { n: 2, word: 'a' },
  { n: 3, word: 'car' },
  { n: 4, word: 'yellow' },
  { n: 5, word: 'see' },
  { n: 6, word: 'ball' },
  { n: 7, word: 'and' },
  { n: 8, word: 'fish' },
  { n: 9, word: 'boy' },
  { n: 10, word: 'I' },
  { n: 11, word: 'airplane' },
  { n: 12, word: 'the' },
  { n: 13, word: 'girl' },
  { n: 14, word: 'little' },
  { n: 15, word: 'in' },
  { n: 16, word: 'box' },
  { n: 17, word: 'green' },
  { n: 18, word: 'put' },
  { n: 19, word: 'chicken' },
  { n: 20, word: 'with' },
  { n: 21, word: 'apple' },
  { n: 22, word: 'is' },
  { n: 23, word: 'big' },
  { n: 24, word: 'spoon' },
  { n: 26, word: 'my' },
  { n: 27, word: 'pencil' },
  { n: 28, word: 'red' },
  { n: 29, word: 'banana' },
  { n: 30, word: 'cow' },
  { n: 31, word: 'find' },
  { n: 32, word: 'egg' },
  { n: 33, word: 'water' },
  { n: 34, word: 'blue' },
  { n: 35, word: 'go' },
  { n: 36, word: 'candy' },
  { n: 37, word: 'has' },
  { n: 38, word: 'mother' },
  { n: 39, word: 'eat' },
  { n: 40, word: 'boat' },
  { n: 41, word: 'you' },
  { n: 42, word: 'orange' },
  { n: 43, word: 'to' },
  { n: 44, word: 'ride' },
  { n: 45, word: 'dog' },
  { n: 46, word: 'under' },
  { n: 47, word: 'tree' },
  { n: 48, word: 'long' },
  { n: 49, word: 'flower' },
  { n: 50, word: 'he' },
  { n: 51, word: 'said' },
  { n: 52, word: 'black' },
  { n: 53, word: 'sky' },
  { n: 54, word: 'on' },
  { n: 55, word: 'table' },
  { n: 56, word: 'funny' },
  { n: 57, word: 'up' },
  { n: 58, word: 'bread' },
  { n: 59, word: 'cat' },
  { n: 60, word: 'school' },
  { n: 61, word: 'play' },
  { n: 63, word: 'teacher' },
  { n: 64, word: 'run' },
  { n: 65, word: 'it' },
  { n: 66, word: 'purple' },
  { n: 67, word: 'she' },
  { n: 68, word: 'father' },
  { n: 69, word: 'are' },
  { n: 70, word: 'bird' },
  { n: 71, word: 'not' },
  { n: 72, word: 'chair' },
  { n: 73, word: 'telephone' },
  { n: 74, word: 'or' },
  { n: 75, word: 'grass' },
  { n: 76, word: 'sit' },
  { n: 77, word: 'ice cream' },
  { n: 78, word: 'there' },
  { n: 79, word: 'we' },
  { n: 80, word: 'book' },
  { n: 81, word: 'happy' },
  { n: 82, word: 'can' },
  { n: 83, word: 'paper' },
  { n: 84, word: 'one' },
  { n: 85, word: 'drink' },
  { n: 86, word: 'at' },
  { n: 87, word: 'they' },
  { n: 88, word: 'cup' },
  { n: 89, word: 'fast' },
  { n: 90, word: 'will' },
  { n: 91, word: 'man' },
  { n: 92, word: 'have' },
  { n: 93, word: 'elephant' },
  { n: 94, word: 'slow' },
  { n: 95, word: 'scissors' },
  { n: 96, word: 'take' },
  { n: 97, word: 'good' },
  { n: 98, word: 'six' },
  { n: 99, word: 'what' },
  { n: 100, word: 'for' },
  { n: 101, word: 'zoo' },
  { n: 102, word: 'milk' },
  { n: 103, word: 'rabbit' },
  { n: 104, word: 'her' },
  { n: 105, word: 'jump' },
  { n: 106, word: 'two' },
  { n: 107, word: 'where' },
  { n: 108, word: 'mouse' },
  { n: 109, word: 'saw' },
  { n: 110, word: 'pretty' },
  { n: 111, word: 'bike' },
  { n: 112, word: 'me' },
  { n: 113, word: 'this' },
  { n: 114, word: 'animal' },
  { n: 115, word: 'come' },
  { n: 116, word: 'him' },
  { n: 117, word: 'knife' },
  { n: 118, word: 'out' },
  { n: 119, word: 'brown' },
  { n: 120, word: 'was' },
  { n: 121, word: 'picture' },
  { n: 122, word: 'by' },
  { n: 123, word: 'magazine' },
  { n: 124, word: 'all' },
  { n: 125, word: 'eight' },
  { n: 126, word: 'game' },
  { n: 127, word: 'had' },
  { n: 128, word: 'squirrel' },
  { n: 129, word: 'look' },
  { n: 130, word: 'pink' },
  { n: 131, word: 'vegetable' },
  { n: 132, word: 'of' },
  { n: 133, word: 'plate' },
  { n: 134, word: 'new' },
  { n: 135, word: 'help' },
  { n: 136, word: 'balloon' },
  { n: 138, word: 'away' },
  { n: 139, word: 'but' },
  { n: 140, word: 'street' },
  { n: 141, word: 'do' },
  { n: 142, word: 'when' },
  { n: 143, word: 'baby' },
  { n: 144, word: 'get' },
  { n: 145, word: 'window' },
  { n: 146, word: 'am' },
  { n: 147, word: 'high' },
  { n: 148, word: 'us' },
  { n: 149, word: 'children' },
  { n: 150, word: 'were' },
  { n: 151, word: 'bear' },
  { n: 152, word: 'other' },
  { n: 153, word: 'give' },
]

// Practice pool: only words up to this lesson number are used in rounds.
// Zoe has the first 10 down; set to 12 to ease in new words.
export const PRACTICE_THROUGH_LESSON = 12

export function activeWords(): SightWord[] {
  return SIGHT_WORDS.filter((w) => w.n <= PRACTICE_THROUGH_LESSON)
}

// Emoji "pictures" for the concrete words. Function words (a, the, and, I, see…)
// are intentionally left out — they have no picture, so they're skipped in the
// picture-matching game. Each emoji is unique so a picture maps to one word.
export const WORD_EMOJI: Record<string, string> = {
  horse: '🐴', car: '🚗', ball: '⚽', fish: '🐟', boy: '👦', airplane: '✈️',
  girl: '👧', box: '📦', chicken: '🐔', apple: '🍎', spoon: '🥄', pencil: '✏️',
  banana: '🍌', cow: '🐄', egg: '🥚', water: '💧', candy: '🍬', mother: '👩',
  boat: '⛵', orange: '🍊', dog: '🐶', tree: '🌳', flower: '🌸', cat: '🐱',
  bread: '🍞', school: '🏫', teacher: '🧑‍🏫', bird: '🐦', chair: '🪑',
  telephone: '☎️', grass: '🌿', 'ice cream': '🍦', book: '📖', paper: '📄',
  cup: '☕', man: '👨', elephant: '🐘', scissors: '✂️', zoo: '🦁', milk: '🥛',
  rabbit: '🐰', mouse: '🐭', bike: '🚲', knife: '🔪', picture: '🖼️',
  magazine: '📰', game: '🎲', squirrel: '🐿️', vegetable: '🥕', plate: '🍽️',
  balloon: '🎈', street: '🛣️', baby: '👶', window: '🪟', bear: '🐻',
  father: '🧔', children: '🧒',
  // colors
  yellow: '🟡', green: '🟢', red: '🔴', blue: '🔵', black: '⚫', purple: '🟣',
  brown: '🟤', pink: '🩷',
  // numbers
  one: '1️⃣', two: '2️⃣', six: '6️⃣', eight: '8️⃣',
  // clear actions / things
  eat: '😋', drink: '🥤', run: '🏃', jump: '🤸', ride: '🚴', look: '👀', give: '🎁',
}

// Active words that have a picture — used by the picture-matching game.
export function imageableActiveWords(): { word: string; emoji: string }[] {
  return activeWords()
    .filter((w) => WORD_EMOJI[w.word])
    .map((w) => ({ word: w.word, emoji: WORD_EMOJI[w.word] }))
}

export const ROUND_SIZE = 6
export const CHOICES = 3
